In [2]:
import tensorflow as tf

In [3]:
x = tf.random.uniform([3,3])

print("Is there a GPU available: "),
print(tf.config.list_physical_devices("GPU"))

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
[]
Is the Tensor on GPU #0:  
False


In [4]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [8]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)
x = tf.ones((3, 3))
y = model(x)
print(y)

tf.Tensor(
[[ 0.3504456  -0.01399934 -0.09554702 -0.16037229]
 [ 0.3504456  -0.01399934 -0.09554702 -0.16037229]
 [ 0.3504456  -0.01399934 -0.09554702 -0.16037229]], shape=(3, 4), dtype=float32)


In [9]:
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

In [10]:
model = keras.Sequential(name="my_sequential")
model.add(layers.Dense(2, activation="relu", name="layer1"))
model.add(layers.Dense(3, activation="relu", name="layer2"))
model.add(layers.Dense(4, name="layer3"))

In [11]:
print(len(model.layers))

3


In [12]:
model.pop()
print(len(model.layers))

2


In [13]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
)

x = tf.ones((1, 4))
y = model(x)
print("Number of weights after calling the model:", len(model.weights))

Number of weights after calling the model: 6


In [14]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (1, 2)                      │              10 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (1, 3)                      │               9 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (1, 4)                      │              16 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 35 (140.00 B)

 Trainable params: 35 (140.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model = keras.Sequential()
model.add(layers.Input(shape=(4,)))
model.add(layers.Dense(2, activation="relu"))

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 10 (40.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu", input_shape=(4,)))



In [18]:
initial_model = keras.Sequential(
    [
        layers.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers],
)

x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
print(features)

[<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
array([[[[0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265],
         [0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265],
         [0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265],
         ...,
         [0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265],
         [0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265],
         [0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265]],

        [[0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265],
         [0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265],
         [0.74835277, 0.32145175, 0.        , ..., 0.        ,
          0.        , 0.62050265],
         ...,
         [0.74835277, 0.3214

In [19]:
inputs = keras.Input(shape=(784,), name="digits")
x = layers.Dense(64, activation="relu", name="dense_1")(inputs)
x = layers.Dense(64, activation="relu", name="dense_2")(x)
outputs = layers.Dense(10, activation="softmax", name="predictions")(x)

model = keras.Model(inputs=inputs, outputs=outputs)

In [20]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
print(x_train.shape)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step
(60000, 28, 28)


In [21]:
x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255

y_train = y_train.astype("float32")
y_test = y_test.astype("float32")

In [22]:
x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]

In [23]:
model.compile(
    optimizer=keras.optimizers.RMSprop(),  # Optimizer
    # Loss function to minimize
    loss=keras.losses.SparseCategoricalCrossentropy(),
    # List of metrics to monitor
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)

In [24]:
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)

In [27]:
print("Fit model on training data")
history = model.fit(
    x_train,
    y_train,
    batch_size=64,
    epochs=2,
    validation_data=(x_val, y_val),
)

Fit model on training data
Epoch 1/2
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.1210 - sparse_categorical_accuracy: 0.9632 - val_loss: 0.1131 - val_sparse_categorical_accuracy: 0.9665
Epoch 2/2
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0971 - sparse_categorical_accuracy: 0.9700 - val_loss: 0.1082 - val_sparse_categorical_accuracy: 0.9678


In [26]:
history.history

{'loss': [0.348223477602005, 0.16712021827697754],
 'sparse_categorical_accuracy': [0.9003199934959412, 0.9504799842834473],
 'val_loss': [0.2182961404323578, 0.13365952670574188],
 'val_sparse_categorical_accuracy': [0.9362999796867371, 0.9606999754905701]}

In [28]:
print("Evaluate on test data")
results = model.evaluate(x_test, y_test, batch_size=128)
print("test loss, test acc:", results)

print("Generate predictions for 3 samples")
predictions = model.predict(x_test[:3])
print("predictions shape:", predictions.shape)

Evaluate on test data
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1227 - sparse_categorical_accuracy: 0.9636
test loss, test acc: [0.10940217226743698, 0.9684000015258789]
Generate predictions for 3 samples
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
predictions shape: (3, 10)


In [29]:
print(predictions)

[[1.29541689e-07 3.09196615e-08 3.49675247e-05 1.06478314e-04
  1.02981712e-11 5.03233677e-09 6.37989824e-14 9.99853492e-01
  3.42268049e-06 1.58747105e-06]
 [2.01931499e-07 5.90013042e-05 9.98767912e-01 9.86749772e-04
  1.06339049e-10 6.42812893e-06 4.24284881e-05 1.76855828e-08
  1.37327166e-04 1.78973381e-11]
 [2.32332377e-06 9.96268094e-01 1.07333239e-03 9.25803106e-05
  8.77430557e-06 2.84595240e-04 2.25268668e-04 1.38040923e-03
  6.62975304e-04 1.63442235e-06]]
